site_name: 'Awesome-Open-Science'
site_description: 'Awesome List of Open Science Tools'
site_author: 'Tyson L Swetnam'
site_url: https://tysonswetnam.com/awesome-open-science

# Repository
repo_name: awesome-open-science
repo_url: https://github.com/tyson-swetnam/awesome-open-science
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2022 Tyson Lee Swetnam'

# Page tree
nav:
  - Home: index.md
  - Research: 
    - Funding Opportunities: funding.md
    - Data Management Plans: dmp.md
  - Data: data.md   
  - Search Engines: search.md
  - Open Access:
    - Publishing: publishing.md
    - Reviews: reviews.md
  - Distributed Computing:
    - Cyberinfrastructure: cyberinfrastructure.md
    - Cloud: cloud.md
  - Hardware: hardware.md
  - Software: software.md  
  - Education: edu.md 
  - Networks: networks.md

# Configuration

theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Montserrat
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: material/sunglasses
    admonition:
      note: material/map-marker-radius-outline

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-6639-7181
    - icon: fontawesome/brands/github
      link: https://github.com/tyson-swetnam/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tswetnam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tyson-swetnam
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/tswetnam
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC5xPt9KZHccC0ehMNEkINzQ
  analytics:
    provider: google
    property: G-NYETZFD8DN
  
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
